release:
  type: 'plugin'
  languagesDir: './languages/'
  files:
    - "./**/*.*"
    - "!./**/*.map"
    - "!./**/build/**/*.*"
    - "!./**/.git/**"
    - "!./**/.gitignore"
    - "!./**/.gitmodules"
    - "!./**/gulpfile.js"
    - "!./**/gruntfile.js"
    - "!./**/gulp/**/*.*"
    - "!./**/package.json"
    - "!./**/package-lock.json"
    - "!./**/bower.json"
    - "!./**/composer.json"
    - "!./**/node_modules/**/*.*"
    - "!./**/bower_components/**/*.*"
    - "!./**/README.md"
    - "!./**/*.zip"
    - "!./**/.babelrc"
    - "!./**/config.yml"
    - "!./**/webpack.config.js"
    - "!./**/gulpfile.babel.js"
    - "!./example-json/**/*.*"
    - "!./core/library/rbm-field-helpers/bin/*.*"
    - "!./core/library/rbm-field-helpers/assets/src/**/*.*"